spring:
  application:
    name: ms-products
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      acks: all
      #      retries: 10
      properties:
        #        retry:
        #          backoff:
        #            ms: 1000
        delivery:
          timeout:
            ms: 120000
            # the maximum time that producer will wait for entire send operation to complete, including:
            # - time to send the request
            # - time waits for ack
            # - time waits for retry send failures
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000 # time the producer can wait after sending a single request
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
services:
  products:
    kafka:
      topic:
        name: product-created-events-topic
        partition: 3
        replicas: 3
        min:
          insync:
            replicas: 2

server:
  port: 0

